- name: Add multiple Jenkins credentials
  hosts: localhost
  vars_files:
    - token.yml

  tasks:
    - name: Add CUSTOM scope credential
      jenkins_credential:
        id: "CUSTOM"
        type: "scope"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "Custom scope credential"
        inc_path:
          - "include/path"
          - "include/path2"
        exc_path:
          - "exclude/path"
          - "exclude/path2"
        inc_hostname:
          - "included-hostname"
          - "included-hostname2"
        exc_hostname:
          - "excluded-hostname"
          - "excluded-hostname2"
        schemes:
          - "http"
          - "https"
        inc_hostname_port:
          - "included-hostname:7000"
          - "included-hostname2:7000"
        exc_hostname_port:
          - "excluded-hostname:7000"
          - "excluded-hostname2:7000"

    - name: Add file credential
      jenkins_credential:
        id: "file-id"
        type: "file"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "File credential"
        file_path: "my-secret.pem"

    - name: Add userAndPass credential
      jenkins_credential:
        id: "userpass-id"
        type: "userAndPass"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "User and password credential"
        username: "user2"
        password: "pass1"

    - name: Add userAndPass credential
      jenkins_credential:
        scope: "CUSTOM"
        id: "userpass-id"
        type: "userAndPass"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "User and password credential"
        username: "user2"
        password: "pass1"

    - name: Add text credential
      jenkins_credential:
        id: "text-id"
        type: "text"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "Text credential"
        secret: "mysecrettext"

    - name: Add githubApp credential
      jenkins_credential:
        id: "githubapp-id"
        type: "githubApp"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "GitHub App credential"
        appID: "12345"
        file_path: "my-secret.pem"
        owner: "github_owner"

    - name: Add sshKey credential
      jenkins_credential:
        id: "sshkey-id"
        type: "sshKey"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "SSH key credential"
        username: "sshuser"
        file_path: "my-secret.pem"
        passphrase: 1234

    - name: Add certificate credential (p12)
      jenkins_credential:
        id: "certificate-id"
        type: "certificate"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "Certificate credential"
        password: "12345678901234"
        file_path: "certificate.p12"

    - name: Add certificate credential (pem)
      jenkins_credential:
        id: "certificate-id-pem"
        type: "certificate"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "Certificate credential (pem)"
        file_path: "cert.pem"
        private_key_path: "private.key"
