- name: Add multiple Jenkins credentials
  hosts: localhost
  vars_files:
    - token.yml

  tasks:
    - name: Add CUSTOM scope credential
      jenkins_credential:
        id: "CUSTOM"
        type: "scope"
        jenkinsUser: "ruff"
        token: "{{ token }}"
        description: "Custom scope credential"
        incPath:
          - "include/path"
          - "include/path2"
        excPath:
          - "exclude/path"
          - "exclude/path2"
        incHostName:
          - "included-hostname"
          - "included-hostname2"
        excHostName:
          - "excluded-hostname"
          - "excluded-hostname2"
        schemes:
          - "http"
          - "https"
        incHostNamePort:
          - "included-hostname:7000"
          - "included-hostname2:7000"
        excHostNamePort:
          - "excluded-hostname:7000"
          - "excluded-hostname2:7000"

    - name: Add file credential
      jenkins_credential:
        id: "file-id"
        type: "file"
        jenkinsUser: "ruff"
        token: "{{ token }}"
        description: "File credential"
        filePath: "my-secret.pem"

    - name: Add userAndPass credential
      jenkins_credential:
        id: "userpass-id"
        type: "userAndPass"
        jenkinsUser: "ruff"
        token: "{{ token }}"
        description: "User and password credential"
        username: "user2"
        password: "pass1"

    - name: Add userAndPass credential
      jenkins_credential:
        scope: "CUSTOM"
        id: "userpass-id"
        type: "userAndPass"
        jenkinsUser: "ruff"
        token: "{{ token }}"
        description: "User and password credential"
        username: "user2"
        password: "pass1"

    - name: Add text credential
      jenkins_credential:
        id: "text-id"
        type: "text"
        jenkinsUser: "ruff"
        token: "{{ token }}"
        description: "Text credential"
        secret: "mysecrettext"

    - name: Add githubApp credential
      jenkins_credential:
        id: "githubapp-id"
        type: "githubApp"
        jenkinsUser: "ruff"
        token: "{{ token }}"
        description: "GitHub App credential"
        appID: "12345"
        filePath: "my-secret.pem"
        owner: "github_owner"

    - name: Add sshKey credential
      jenkins_credential:
        id: "sshkey-id"
        type: "sshKey"
        jenkinsUser: "ruff"
        token: "{{ token }}"
        description: "SSH key credential"
        username: "sshuser"
        filePath: "my-secret.pem"
        passphrase: 1234

    - name: Add certificate credential (p12)
      jenkins_credential:
        id: "certificate-id"
        type: "certificate"
        jenkinsUser: "ruff"
        token: "{{ token }}"
        description: "Certificate credential"
        password: "12345678901234"
        filePath: "certificate.p12"

    - name: Add certificate credential (pem)
      jenkins_credential:
        id: "certificate-id-pem"
        type: "certificate"
        jenkinsUser: "ruff"
        token: "{{ token }}"
        description: "Certificate credential (pem)"
        filePath: "cert.pem"
        privateKeyPath: "private.key"
