- name: Add multiple Jenkins credentials
  hosts: localhost
  vars_files:
    - token.yml

  tasks:
    - name: Generate token
      jenkins_credential:
        name: "test-token"
        jenkins_user: "ruffnut"
        jenkins_password: "barf"
        type: "token"
      no_log: yes
      register: token_result

    - name: Set token facts
      set_fact:
        token: "{{ token_result.token }}"
        tokenUuid: "{{ token_result.tokenUuid }}"

    - name: Add CUSTOM scope credential
      jenkins_credential:
        id: "CUSTOM"
        type: "scope"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "Custom scope credential"
        inc_path:
          - "include/path"
          - "include/path2"
        exc_path:
          - "exclude/path"
          - "exclude/path2"
        inc_hostname:
          - "included-hostname"
          - "included-hostname2"
        exc_hostname:
          - "excluded-hostname"
          - "excluded-hostname2"
        schemes:
          - "http"
          - "https"
        inc_hostname_port:
          - "included-hostname:7000"
          - "included-hostname2:7000"
        exc_hostname_port:
          - "excluded-hostname:7000"
          - "excluded-hostname2:7000"

    - name: Add user_and_pass credential
      jenkins_credential:
        id: "userpass-id"
        type: "user_and_pass"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "User and password credential"
        username: "user2"
        password: "pass1"

    - name: Add file credential
      jenkins_credential:
        id: "file-id"
        type: "file"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "File credential"
        file_path: "my-secret.pem"

    - name: Add user_and_pass credential to CUSTOM
      jenkins_credential:
        scope: "CUSTOM"
        id: "userpass-id"
        type: "user_and_pass"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "User and password credential"
        username: "user2"
        password: "pass1"

    - name: Add user_and_pass credential to folder
      jenkins_credential:
        id: "tst-userpass-id"
        type: "user_and_pass"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "tst User and password credential"
        username: "tstuser"
        password: "tstpass1"
        location: "folder"
        url: "http://localhost:8080/job/test"

    - name: Add text credential
      jenkins_credential:
        id: "text-id"
        type: "text"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "Text credential"
        secret: "mysecrettext"

    - name: Add githubApp credential
      jenkins_credential:
        id: "githubapp-id"
        type: "github_app"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "GitHub App credential"
        appID: "12345"
        file_path: "github.pem"
        owner: "github_owner"

    - name: Add sshKey credential
      jenkins_credential:
        id: "sshkey-id"
        type: "ssh_key"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "SSH key credential"
        username: "sshuser"
        file_path: "ssh_key"
        passphrase: 1234

    - name: Add certificate credential (p12)
      jenkins_credential:
        id: "certificate-id"
        type: "certificate"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "Certificate credential"
        password: "12345678901234"
        file_path: "certificate.p12"

    - name: Add certificate credential (pem)
      jenkins_credential:
        id: "certificate-id-pem"
        type: "certificate"
        jenkins_user: "ruffnut"
        token: "{{ token }}"
        description: "Certificate credential (pem)"
        file_path: "cert.pem"
        private_key_path: "private.key"
