---
- name: Edit multiple Jenkins credentials
  hosts: localhost
  gather_facts: no
  vars_files:
    - token.yml

  tasks:
    - name: Edit CUSTOM scope credential
      jenkins_credential:
        id: "CUSTOM"
        type: "scope"
        jenkins_user: "ruff"
        token: "{{ token }}"
        state: "present"
        description: "New custom scope credential"
        inc_path:
          - "newinclude/path"
          - "newinclude/path2"
        exc_path:
          - "newexclude/path"
          - "newexclude/path2"
        inc_hostname:
          - "newincluded-hostname"
          - "newincluded-hostname2"
        exc_hostname:
          - "newexcluded-hostname"
          - "newexcluded-hostname2"
        schemes:
          - "newhttp"
          - "newhttps"
        inc_hostname_port:
          - "newincluded-hostname:7000"
          - "newincluded-hostname2:7000"
        exc_hostname_port:
          - "newexcluded-hostname:7000"
          - "newexcluded-hostname2:7000"

    - name: Edit userAndPass credential password
      jenkins_credential:
        id: "userpass-id"
        scope: "CUSTOM"
        type: "userAndPass"
        state: "present"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "Edit user/pass credential"
        username: "user2"
        password: "newpass1"

    - name: Edit file credential description (no file change)
      jenkins_credential:
        id: "file-id"
        type: "file"
        state: "present"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "presentd file credential description"
        file_path: "newsecret.pem"

    - name: Edit text credential secret
      jenkins_credential:
        id: "text-id"
        type: "text"
        state: "present"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "edited text credential"
        secret: "newsecrettext"

    - name: Edit githubApp credential private key or description
      jenkins_credential:
        id: "githubapp-id"
        type: "githubApp"
        state: "present"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "edited GitHub App credential"
        appID: "12345"
        file_path: "newsecret.pem"
        owner: "github_owner"

    - name: Edit sshKey credential passPhrase (optional)
      jenkins_credential:
        id: "sshkey-id"
        type: "sshKey"
        state: "present"
        jenkins_user: "ruff"
        token: "{{ token }}"
        description: "edited SSH key credential"
        username: "sshuser"
        file_path: "newsecret.pem"
        passphrase: "newpassphrase"
